### ISSUE TITLE
Your coding challenge is not completed yet

### ISSUE THREAD

**Issue by zahraoui-mohammed** [omartbou/Laravel-vuejs-coding-challenge#2]
missing categories

**Comment by omartbou** [comment]
Can I fix it now ?

**Comment by zahraoui-mohammed** [comment]
Go ahead

**Comment by omartbou** [comment]
Thanks

**Comment by omartbou** [comment]
done

**Comment by zahraoui-mohammed** [comment]
how can I create categories ?

**Comment by omartbou** [comment]
I thought the problem was related to the creation of a product and that the categories weren’t being added to each product. The challenge didn’t mention creating categories from the web just from the command line that I mentioned in readme File.

**Comment by omartbou** [comment]
this is the command php artisan category:create "Category Name"

**Comment by omartbou** [comment]
![image](https://github.com/user-attachments/assets/bf33f053-5102-41d5-a89e-d61dfdc277f2)

**Comment by omartbou** [comment]
am I right ?

**Comment by omartbou** [comment]
@zahraoui-mohammed  hello I made some changes could you check them, thanks
